# Generated by Django 3.2.12 on 2022-03-15 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='utc',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Часовой пояс должен быть от "-12" до "+12" или "0"', regex='^[+-]?([01]\\d?)|(\\d)')]),
        ),
    ]
